insert into application_user (version, id, username,name,hashed_password,profile_picture) values (1, '1','user','John Normal','$2a$10$xdbKoM48VySZqVSU/cSlVeJn0Z04XCZ7KZBjUBC00eKo5uLswyOpe','')
insert into user_roles (user_id, roles) values ('1', 'USER')
insert into application_user (version, id, username,name,hashed_password,profile_picture) values (1, '2','admin','Emma Powerful','$2a$10$jpLNVNeA7Ar/ZQ2DKbKCm.MuT2ESe.Qop96jipKMq7RaUgCoQedV.','')
insert into user_roles (user_id, roles) values ('2', 'USER')
insert into user_roles (user_id, roles) values ('2', 'ADMIN')
insert into quantity_colors (id, name) values ('1', 'Black only')
insert into quantity_colors (id, name) values ('2', 'CMYK')
insert into quantity_colors (id, name) values ('3', 'CMYK + 1 Spot')
insert into quantity_colors (id, name) values ('4', 'CMYK + 2 Spots')
insert into quantity_colors (id, name) values ('5', '1 Spot')
insert into quantity_colors (id, name) values ('6', '2 Spot')
insert into quantity_colors (id, name) values ('7', '3 Spot')
insert into quantity_colors (id, name) values ('8', '4 Spot')
insert into type_of_printer (id, name) values ('1', 'Laser jet')
insert into type_of_printer (id, name) values ('2', 'Ink jet')
insert into type_of_printer (id, name) values ('3', 'Duplicator')
insert into type_of_printer (id, name) values ('4', 'Foil printer')
insert into type_of_material (id, name) values ('1','Plain Paper')
insert into type_of_material (id, name) values ('2','Coated Paper')
insert into type_of_material (id, name) values ('3','Syntetic Paper')
insert into type_of_material (id, name) values ('4','High quality Paper')
insert into type_of_material (id, name) values ('5','Laser jet Film')
insert into type_of_material (id, name) values ('6','Ink jet Paper')
