insert into application_user (version, id, username,name,hashed_password,profile_picture) values (1, '1','user','John Normal','$2a$10$xdbKoM48VySZqVSU/cSlVeJn0Z04XCZ7KZBjUBC00eKo5uLswyOpe','')
insert into user_roles (user_id, roles) values ('1', 'USER')
insert into application_user (version, id, username,name,hashed_password,profile_picture) values (1, '2','admin','Emma Powerful','$2a$10$jpLNVNeA7Ar/ZQ2DKbKCm.MuT2ESe.Qop96jipKMq7RaUgCoQedV.','')
insert into user_roles (user_id, roles) values ('2', 'USER')
insert into user_roles (user_id, roles) values ('2', 'ADMIN')
insert into quantity_colors (id, version, name) values ('1', '1','Black only')
insert into quantity_colors (id, version, name) values ('2', '1','CMYK')
insert into quantity_colors (id, version, name) values ('3', '1','CMYK + 1 Spot')
insert into quantity_colors (id, version, name) values ('4', '1','CMYK + 2 Spots')
insert into quantity_colors (id, version, name) values ('5', '1','1 Spot')
insert into quantity_colors (id, version, name) values ('6', '1','2 Spot')
insert into quantity_colors (id, version, name) values ('7', '1','3 Spot')
insert into quantity_colors (id, version, name) values ('8', '1','4 Spot')
insert into type_of_printer (id, version, name) values ('1', '1','Лазерный')
insert into type_of_printer (id, version, name) values ('2', '1','Струйный')
insert into type_of_printer (id, version, name) values ('3', '1','Трафаретный')
insert into type_of_printer (id, version, name) values ('4', '1','Позолотный')
insert into type_of_material (id, version, name) values ('1', '1','Бумага офсетная')
insert into type_of_material (id, version, name) values ('2', '1','Бумага мелованная')
insert into type_of_material (id, version, name) values ('3', '1','Бумага синтетическая')
insert into type_of_material (id, version, name) values ('4', '1','Бумага высококаландрированная')
insert into type_of_material (id, version, name) values ('5', '1','Пленка для печати на лазерных принтерах')
insert into type_of_material (id, version, name) values ('6', '1','Бумага для струйных принтеров')
insert into print_mashine (id, version, name, clicks, cost, final_cost_of_black_click, final_cost_of_cmyk_click,final_cost_of_spot_click, made_of_clicks, max_print_areax, max_print_areay, price_of_black_click, price_of_cmyk_click, price_of_spot_click, quantity_colors_id, type_of_printer) values ('1', '1','Xerox J75 Press','200000', '850000', '0', '0', '0', '0','488', '330','2.5', '4.5', '0', '2','1')
insert into print_mashine (id, version, name, clicks, cost, final_cost_of_black_click, final_cost_of_cmyk_click,final_cost_of_spot_click, made_of_clicks, max_print_areax, max_print_areay, price_of_black_click, price_of_cmyk_click, price_of_spot_click, quantity_colors_id, type_of_printer) values ('2', '1','Konica Minolta BizHub C6500','100000', '150000', '0', '0', '0', '0','487', '330','2.5', '4.5', '0', '2','1')
insert into print_mashine (id, version, name, clicks, cost, final_cost_of_black_click, final_cost_of_cmyk_click,final_cost_of_spot_click, made_of_clicks, max_print_areax, max_print_areay, price_of_black_click, price_of_cmyk_click, price_of_spot_click, quantity_colors_id, type_of_printer) values ('3', '1','Duplo DP-430','1000000', '85000', '0', '0', '0', '0','420', '297','0.5', '0', '0', '1','3')
